GET http://localhost:3000/movies

###

GET http://localhost:3000/movies/5e67f5eeba7c2052984a4300

###

DELETE http://localhost:3000/movies/5e68cb4e8a6e3b47ec6a022d

###

PATCH http://localhost:3000/movies/5e67f5eeba7c2052984a4300
Content-Type: application/json

{    
    "moviePosterUrl": "https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/3b162218290561.562c7079a41fd.jpg",
    "movieID": "1"
}

###

POST http://localhost:3000/movies
Content-Type: application/json

{    
    "name": "Back to the Future",
    "moviePosterUrl": "https://static.posters.cz/image/750/poster/back-to-the-future-i2795.jpg",
    "movieID": "3",
    "movieYear": "1985",
    "imdbID": "tt0088763",
    "imdbRate": "8.5",
    "trailerUrl": "https://www.youtube.com/watch?v=qvsgGtivCgs",
    "movieGenre": ["Sci-Fi", "Adventure", "Comedy"],
    "movieDuration": "116",
    "movieDescription": "Marty McFly, a 17-year-old high school student, is accidentally sent thirty years into the past in a time-traveling DeLorean invented by his close friend, the eccentric scientist Doc Brown.",
    "movieActors": ["Michael J. Fox", "Christopher Lloyd", "Lea Thompson"]
}