GET http://localhost:3000/movies

###

GET http://localhost:3000/movies/5e67f5eeba7c2052984a4300

###

DELETE http://localhost:3000/movies/5e68bfe1f2cdc12b4c2b5eb9

###

PATCH http://localhost:3000/movies/5e67f5eeba7c2052984a4300
Content-Type: application/json

{    
    "moviePosterUrl": "https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/3b162218290561.562c7079a41fd.jpg",
    "movieID": "1"
}

###

POST http://localhost:3000/movies
Content-Type: application/json

{    
    "name": "Batman",
    "moviePosterUrl": "https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/3b162218290561.562c7079a41fd.jpg",
    "movieID": "1",
    "movieYear": "1989",
    "imdbID": "tt0096895",
    "imdbRate": "7.5",
    "trailerUrl": "https://www.youtube.com/watch?v=dgC9Q0uhX70",
    "movieGenre": ["Action", "Adventure"],
    "movieDuration": "126",
    "movieDescription": "The Dark Knight of Gotham City begins his war on crime with his first major enemy being Jack Napier, a criminal who becomes the clownishly homicidal Joker.",
    "movieActors": ["Michael Keaton", "Jack Nicholson", "Kim Basinger"]
}